-- CREATING THE DATABASE
CREATE DATABASE BLOODSTOCKMANAGEMENT; 

USE BLOODSTOCKMANAGEMENT;


-- CREATE THE BLOODBANK TABLE
CREATE TABLE BLOODBANK(
	BLOODBANKID INT PRIMARY KEY,
    LICENSEID VARCHAR(20) UNIQUE,
    BLOODBANKNAME VARCHAR(225),
    LOCATION VARCHAR(225),
    CONTACT VARCHAR(20)
);

-- CREATE TABLE FOR DONORS
CREATE TABLE DONORS(
    DONORID INT PRIMARY KEY AUTO_INCREMENT,
    BLOODBANKID INT,
    DONORNAME VARCHAR(225),
    CONTACT_NO VARCHAR(20),
    EMAIL VARCHAR(100),
    BLOODGROUP VARCHAR(10),
    LAST_DONATION_DATE DATE,
    FOREIGN KEY (BLOODBANKID) REFERENCES BLOODBANK(BLOODBANKID)
);


-- CREATE TABLE FOR BLOODUNITS 
CREATE TABLE BLOODUNITS(
	BLOODUNITID INT PRIMARY KEY AUTO_INCREMENT,
    BLOODBANKID INT,
    BLOODGROUP VARCHAR(10),
    DONORID INT,
    STATUS VARCHAR(30),
    COLLECTION_DATE DATE,
    EXPIRY_DATE DATE,
    FOREIGN KEY (DONORID) REFERENCES DONORS(DONORID),
    FOREIGN KEY (BLOODBANKID) REFERENCES BLOODBANK(BLOODBANKID)
);

-- ENABLE THE EVENT SCHEDULER
SET GLOBAL EVENT_SCHEDULER = ON;

-- EVENT THAT UPDATES THE STATUS OF A BLOODUNIT IF IT'S EXPIRY DATE IS REACHED 
DROP EVENT IF EXISTS UPDATE_EXPIRED_BLOODUNITS;

CREATE EVENT UPDATE_EXPIRED_BLOODUNITS
ON SCHEDULE EVERY 1 MINUTE
DO
  UPDATE BLOODUNITS
  SET STATUS = 'EXPIRED'
  WHERE EXPIRY_DATE < CURDATE() AND STATUS != 'EXPIRED';


-- CREATE A TABLE TO LOG ALL THE RECENT ACTIVITIES 
CREATE TABLE ACTIVITYLOGS(
	LOGID INT PRIMARY KEY AUTO_INCREMENT,
    BLOODBANKID INT NOT NULL,
    ACTIVITY_TEXT TEXT,
    ACTIVITY_TYPE ENUM('ADD_UNIT','DELETE_UNIT','SEND_NOTIFICATION','USE_UNIT'),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(BLOODBANKID) REFERENCES BLOODBANK(BLOODBANKID)
);
  
    
-- CREATE TABLE FOR HOSPITALS 
CREATE TABLE HOSPITALS(
	HOSPITALID INT PRIMARY KEY,
    LICENSEID VARCHAR(50),
    LOCATION VARCHAR(225)
);
    

-- CREATE TABLE FOR REQUESTS 
CREATE TABLE REQUESTS(
	REQUESTID INT PRIMARY KEY AUTO_INCREMENT,
    HOSPITALID INT,
    BLOODBANKID INT,
    BLOODGROUP VARCHAR(10),
    UNITS INT,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50),
    FOREIGN KEY(HOSPITALID) REFERENCES HOSPITALS(HOSPITALID),
    FOREIGN KEY(BLOODBANKID) REFERENCES BLOODBANK(BLOODBANKID)
);

